### ISSUE TITLE
Linux::PipeMagic-0.03 won't compile on a recent Mac.

### ISSUE THREAD

**Issue by davehodg** [davel/Linux-PipeMagic#2]
MacOS 12.4, 

% gcc -v
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

Get an error complaining that a sub expecting 6 params only gets 4:
```
PipeMagic.xs:57:47: error: too few arguments to function call, expected 6, have 4
    RETVAL = sendfile(fd_out, fd_in, NULL, len);
             ~~~~~~~~              
```

**Comment by davel** [comment]
Hi Dave,

It fails to compile because the MacOS and Linux sendfile(2) syscalls take different arguments.

https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/sendfile.2.html vs https://man7.org/linux/man-pages/man2/sendfile.2.html

It looks like the MacOS (and FreeBSD) version takes more arguments, so perhaps we could have an alternate implementation emulating Linux behaviour. Would that be useful for you?

Unfortunately`tee` and `splice` don't have obvious counterparts on MacOS.

**Comment by davehodg** [comment]
I have tee, no splice. Splice can be brew installed.

How about an OS check in Makefile.PL or somewhere more appropriate?

It's not that useful. I was just trying to so a perl -M which I can do in the docker container.

**Comment by davel** [comment]
> I have tee, no splice. Splice can be brew installed.

Could you point me at the docs? I couldn't find `splice` and `tee` syscalls on MacOS when I searched earlier.
 
> How about an OS check in Makefile.PL or somewhere more appropriate?

I've just pushed out a development release which will hopefully make it fail with ENOSYS on non-Linux OSs. (I don't have a Mac to test on so I am waiting for the testers.)

**Comment by davehodg** [comment]
Oh, syscalls. Never mind.

Thanks for your effort. I’m currently wrestling with a lot of your other code at state51 :)

—
David Hodgkinson
Senior Software Development Engineer
+44 7768 490620

**Comment by davel** [comment]
> Oh, syscalls. Never mind. Thanks for your effort. I’m currently wrestling with a lot of your other code at state51 :)

Enjoy! I have just released a new version should at least compile on MacOS, although returns `ENOSYS` if you actually try to use it. If you have fallback code with `sysread` / `syswrite`, that should be enough to work on MacOS.

https://metacpan.org/release/DLAMBLEY/Linux-PipeMagic-0.04

I reckon you could make `sendfile` work on MacOS / FreeBSD, by defaulting some of the arguments. Patches welcome!
